---
# tasks file for bmc_asset

- name: Post token
  ansible.builtin.uri:
    url: "{{ remedy_login }}"
    method: POST
    headers:
      Content-Type: application/x-www-form-urlencoded
    body:
      "{{ remedy_credentials }}"
    return_content: true
    validate_certs: false
    status_code: 200
  delegate_to: localhost
  run_once: true
  register: output
  changed_when: true
  notify: release remedy token

- name: Set token as fact
  ansible.builtin.set_fact:
    remedy_token: AR-JWT {{ output.content }}
  delegate_to: localhost
  run_once: true
