---
# tasks file for bmc_asset

- name: read asset from bmc remedy
  ansible.builtin.uri:
    url: "{{ remedy_read_asset }}%22{{ inventory_hostname }}%22"
    method: GET
    headers:
      Accept: application/json
      Content-Type: application/json
      Authorization: "{{ remedy_token }}"
    body_format: json
    validate_certs: false
  delegate_to: localhost
  register: output
  changed_when: false
