---
# tasks file for bmc_asset

- name: create token
  ansible.builtin.import_tasks: 01_token.yml

- name: read asset
  ansible.builtin.import_tasks: 02_read_asset.yml

- name: create asset
  ansible.builtin.import_tasks: 03_create_asset.yml
