---
# tasks file for bmc_asset

- name: create token
  ansible.builtin.import_tasks: 01_token.yml

- name: get asset
  ansible.builtin.import_tasks: 02_asset_get.yml

- name: add asset
  ansible.builtin.import_tasks: 03_asset_add.yml
