---
# tasks file for bmc_asset

- name: Create token.
  ansible.builtin.uri:
    url: "{{ remedy_login }}"
    method: POST
    headers:
      Content-Type: application/x-www-form-urlencoded
    body:
      "{{ remedy_credentials }}"
    return_content: true
    validate_certs: false
    status_code: 200
  delegate_to: localhost
  run_once: true
  register: output
  changed_when: true
  notify: Release remedy token

- name: Set token as fact.
  ansible.builtin.set_fact:
    remedy_token: AR-JWT {{ output.content }}
  delegate_to: localhost
  run_once: true

- name: Read asset from BMC Remedy.
  ansible.builtin.uri:
    url: "{{ remedy_read_asset }}%22{{ inventory_hostname }}%22"
    method: GET
    headers:
      Accept: application/json
      Content-Type: application/json
      Authorization: "{{ remedy_token }}"
    validate_certs: false
  delegate_to: localhost
  register: output
  changed_when: false

- name: Create asset in BMC Remedy.
  ansible.builtin.uri:
    url: "{{ remedy_create_asset }}"
    method: POST
    headers:
      Accept: application/json
      Content-Type: application/json
      Authorization: "{{ remedy_token }}"
    body_format: json
    body:
      values:
        Name: "{{ inventory_hostname }}"
        Asset ID+: "{{ inventory_hostname }}"
        Serial Number: "{{ ansible_facts.net_serialnum }}"
        System Role: "{{ system_role }}"
        AssetLifecycleStatus: "{{ assetlifecyclestatus }}"
        Category: "{{ catagory }}"
        Type: "{{ catagory_type }}"
        Model Number: "{{ ansible_facts.net_model }}"
        Data Set Id: BMC.ASSET
    validate_certs: false
    status_code: 204
  when: output['json']['entries'][0] is undefined
  delegate_to: localhost
  changed_when: true
