---
# handlers file for remedy.

- name: Release remedy token.
  ansible.builtin.uri:
    url: "{{ __remedy_logout }}"
    method: POST
    headers:
      Authorization: "AR-JWT {{ __remedy_token_output['content'] }}"
    validate_certs: false
    status_code: 204
  delegate_to: localhost
  run_once: true
