---
# handlers file for bmc_asset

- name: release token
  ansible.builtin.uri:
    url: "{{ logout }}"
    method: POST
    headers:
      Authorization: "{{ token }}"
    validate_certs: false
    status_code: 204
  delegate_to: localhost
  run_once: true
