---
# handlers file for remedy

- name: Release remedy token.
  ansible.builtin.uri:
    url: "{{ remedy_logout }}"
    method: POST
    headers:
      Authorization: "{{ remedy_token }}"
    validate_certs: false
    status_code: 204
  delegate_to: localhost
  run_once: true
