---
# handlers file for bmc_asset

- name: release bmc token
  ansible.builtin.uri:
    url: "{{ remedy_api }}/jwt/logout"
    method: POST
    headers:
      Authorization: "{{ remedy_token }}"
    validate_certs: false
    status_code: 204
  delegate_to: localhost
  run_once: true
